workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Initialize iOS files
        script: |
          flutter create --platforms=ios .
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -exec cd "$(dirname "{}")" \; -exec pod install \;
      - name: Build iOS IPA
        script: |
          # 這裡使用 --no-codesign 僅作為示範。
          # 若要產生可安裝的 IPA，您需要在 Codemagic 上設定 Code signing identity (憑證與描述檔)
          # 並移除 --no-codesign 參數。
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - "*.dSYM.zip"
    publishing:
      email:
        recipients:
          - user@example.com # 請替換為您的 Email
