workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Complete Setup and Build
        script: |
          # 1. 環境初始化
          flutter pub get
          
          # 2. 確保 iOS 專案結構與權限說明 (Info.plist)
          rm -rf ios
          flutter create . --platforms ios
          
          # 強制寫入定位說明文字
          sed -i '' '/<dict>/a \
          <key>NSLocationWhenInUseUsageDescription</key>\
          <string>需要定位權限以在地圖上顯示您附近的 AED。</string>\
          <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>\
          <string>需要定位權限以在地圖上顯示您附近的 AED。</string>' ios/Runner/Info.plist

          # 3. 注入定位權限開關到 Podfile
          sed -i '' "1i\\
          ENV['PERMISSION_LOCATION'] = '1'\\
          " ios/Podfile

          # 4. 正式開始編譯 (這步大約需要 1-2 分鐘)
          flutter build ipa --no-codesign --release

          # 5. 暴力路徑打包
          mkdir -p build/ios/ipa
          export APP_PATH="build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app"
          
          if [ -d "$APP_PATH" ]; then
            mkdir -p Payload
            cp -r "$APP_PATH" Payload/
            zip -r Runner.ipa Payload
            mv Runner.ipa build/ios/ipa/
            echo "IPA 打包完成！"
          else
            echo "找不到編譯成品，請檢查 Build 日誌！"
            exit 1
          fi
          
    artifacts:
      - build/ios/ipa/*.ipa