workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Complete Build and Auto Export
        script: |
          # 1. 初始化與注入定位權限 (Info.plist & Podfile)
          flutter pub get
          rm -rf ios
          flutter create . --platforms ios
          
          sed -i '' '/<dict>/a \
          <key>NSLocationWhenInUseUsageDescription</key>\
          <string>需要定位權限以在地圖上顯示您附近的 AED。</string>\
          <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>\
          <string>需要定位權限以在地圖上顯示您附近的 AED。</string>' ios/Runner/Info.plist

          sed -i '' "1i\\
          ENV['PERMISSION_LOCATION'] = '1'\\
          " ios/Podfile

          # 2. 開始編譯
          flutter build ipa --no-codesign --release

          # 3. 【全自動搜索大法】
          # 不管編譯在哪裡，直接把 Runner.ipa 找出來並打包放到根目錄
          export APP_PATH=$(find build/ios/archive -name "Runner.app" | head -n 1)
          mkdir -p Payload
          cp -r "$APP_PATH" Payload/
          zip -r Runner.ipa Payload
          
          # 搬到最外層，讓 Codemagic 絕對看得到
          mv Runner.ipa $FCI_BUILD_DIR/
          echo "IPA 已就位！"
          
    artifacts:
      - "*.ipa"