workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Initialize iOS files
        script: |
          flutter create --platforms=ios .
          # Overwrite Podfile to include permission_handler macros
          cat > ios/Podfile <<EOF
          platform :ios, '12.0'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          # definition of the Podfile
          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
            end

            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig and running flutter pub get"
          end

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
                  '\$(inherited)',
                  'PERMISSION_CAMERA=1',
                  'PERMISSION_MICROPHONE=1',
                  'PERMISSION_LOCATION=1',
                ]
              end
            end
          end
          EOF
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -exec cd "$(dirname "{}")" \; -exec pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
          # Manually package the unsigned app into an IPA so artifacts can pick it up
          cd build/ios/archive/Runner.xcarchive/Products/Applications
          mkdir Payload
          cp -r Runner.app Payload
          zip -r Runner.ipa Payload
          mkdir -p ../../../../ipa
          mv Runner.ipa ../../../../ipa/
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - "*.dSYM.zip"
    publishing:
      email:
        recipients:
          - user@example.com # 請替換為您的 Email
