workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Hard Reset & Package Upgrade
        script: |
          # 1. 砍掉重練 Android 專案
          rm -rf android
          flutter create . --platforms android

          # 2. 【核心修復】強制全體升級！
          # 直接把這三個最常鬧 Registrar 錯誤的套件灌到最新版
          flutter pub add permission_handler geolocator workmanager
          
          # 3. 確保所有相依套件也跟著升級
          flutter pub upgrade --major-versions

          # 4. 注入 Android 權限
          sed -i '' '/<application/i \
          <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> \
          <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" /> \
          <uses-permission android:name="android.permission.INTERNET" />' android/app/src/main/AndroidManifest.xml

          # 5. 編譯 APK
          flutter build apk --debug
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk