workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fix Permissions & Initialize
        script: |
          # 1. 確保 Podfile 有定位開關 (解決按鈕沒反應問題)
          # 如果檔案不存在就產生，存在就注入
          flutter pub get
          if [ -f ios/Podfile ]; then
            sed -i '' "1i\\
            ENV['PERMISSION_LOCATION'] = '1'\\
            " ios/Podfile
          fi

          # 2. 強制確保 Info.plist 有定位說明 (解決設定裡沒選項問題)
          # 這會檢查有沒有 Permissions 標籤，沒有就補上
          sed -i '' '/<dict>/a \
          <key>NSLocationWhenInUseUsageDescription</key>\
          <string>需要定位權限以在地圖上顯示您附近的 AED。</string>\
          <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>\
          <string>需要定位權限以在地圖上顯示您附近的 AED。</string>' ios/Runner/Info.plist

      - name: Build and Pack
        script: |
          # 3. 編譯 IPA
          flutter build ipa --no-codesign --release

          # 4. 【絕對路徑搬運】直接把檔案抓到最外層家門口
          mkdir -p Payload
          cp -r build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app Payload/
          zip -r Runner.ipa Payload
          
          # 搬移到 Codemagic 規定的出貨區
          mkdir -p build/ios/ipa
          mv Runner.ipa build/ios/ipa/
          
    artifacts:
      - build/ios/ipa/*.ipa