workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Complete Build and Force Export
        script: |
          flutter pub get
          rm -rf ios
          flutter create . --platforms ios
          sed -i '' '/<dict>/a \
          <key>NSLocationWhenInUseUsageDescription</key>\
          <string>需要定位權限以在地圖上顯示您附近的 AED。</string>\
          <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>\
          <string>需要定位權限以在地圖上顯示您附近的 AED。</string>' ios/Runner/Info.plist
          sed -i '' "1i\\
          ENV['PERMISSION_LOCATION'] = '1'\\
          " ios/Podfile
          flutter build ipa --no-codesign --release
          mkdir -p $FCI_BUILD_DIR/build/ios/ipa
          cd build/ios/archive/Runner.xcarchive/Products/Applications
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r Runner.ipa Payload
          mv Runner.ipa $FCI_BUILD_DIR/build/ios/ipa/
    artifacts:
      - build/ios/ipa/*.ipa