workflows:
  android-debug:
    name: Android Debug
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Initialize Android and Permissions
        script: |
          # 1. 初始化 Android 專案
          flutter create . --platforms android

          # 2. 注入 Android 權限到 AndroidManifest.xml
          MAN_PATH="android/app/src/main/AndroidManifest.xml"
          
          # 確保檔案存在後注入權限標籤
          if [ -f "$MAN_PATH" ]; then
             sed -i '' '/<application/i \
             <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>\
             <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>\
             <uses-permission android:name="android.permission.INTERNET"/>' "$MAN_PATH"
             echo "Permissions injected into AndroidManifest.xml"
          else
             echo "Error: AndroidManifest.xml not found at $MAN_PATH"
             exit 1
          fi

      - name: Build Android APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk