workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Fix Dependencies & Build
        script: |
          # 1. 產生 Android 專案
          flutter create . --platforms android

          # 2. 【關鍵修復】強制更新套件到最新版
          # 這一行會把 permission_handler 從 10.x 升級到最新版 (11+ 或 12+)
          # 徹底解決 Registrar 找不到的問題
          flutter pub add permission_handler geolocator

          # 3. 注入 Android 權限
          sed -i '' '/<application/i \
          <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> \
          <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" /> \
          <uses-permission android:name="android.permission.INTERNET" />' android/app/src/main/AndroidManifest.xml

          # 4. 編譯
          flutter build apk --debug
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk